### ISSUE TITLE
The above error occurred in the <Gamepad> component:

### ISSUE THREAD

**Issue by ghost** [SBRK/react-gamepad#1]
react-dom.development.js:9747 The above error occurred in the <Gamepad> component:
    in Gamepad (created by Home)
    in div (created by Home)
    in div (created by Home)
    in Home (created by HomePage)
    in HomePage (created by Route)
    in Route (created by _default)
    in Switch (created by _default)
    in div (created by App)
    in App (created by _default)
    in _default (created by Root)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Root)
    in Provider (created by Root)
    in Root
    in AppContainer

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

React.Children.only | @ | reactHotLoader.js:64
-- | -- | --
  | render | @ | Gamepad.js:225
  | proxiedRender | @ | createClassProxy.js:93
  | finishClassComponent | @ | react-dom.development.js:7873
  | updateClassComponent | @ | react-dom.development.js:7850
  | beginWork | @ | react-dom.development.js:8225
  | performUnitOfWork | @ | react-dom.development.js:10224
  | workLoop | @ | react-dom.development.js:10288
  | callCallback | @ | react-dom.development.js:542
  | invokeGuardedCallbackDev | @ | react-dom.development.js:581
  | invokeGuardedCallback | @ | react-dom.development.js:438
  | renderRoot | @ | react-dom.development.js:10366
  | performWorkOnRoot | @ | react-dom.development.js:11014
  | performWork | @ | react-dom.development.js:10967
  | requestWork | @ | react-dom.development.js:10878
  | scheduleWorkImpl | @ | react-dom.development.js:10732
  | scheduleWork | @ | react-dom.development.js:10689
  | scheduleTopLevelUpdate | @ | react-dom.development.js:11193
  | updateContainer | @ | react-dom.development.js:11231
  | (anonymous) | @ | react-dom.development.js:15226
  | unbatchedUpdates | @ | react-dom.development.js:11102
  | renderSubtreeIntoContainer | @ | react-dom.development.js:15225
  | render | @ | react-dom.development.js:15290
  | (anonymous) | @ | index.js:10
  | ./app/index.js | @ | renderer.dev.js:1687
  | __webpack_require__ | @ | bootstrap eb6b1c4…:678
  | fn | @ | bootstrap eb6b1c4…:88
  | 0 | @ | only-dev-server.js:71
  | __webpack_require__ | @ | bootstrap eb6b1c4…:678
  | module.exports../app/actions/counter.js.Object.defineProperty.value | @ | bootstrap eb6b1c4…:724
  | (anonymous) | @ | bootstrap eb6b1c4…:724

**Comment by SBRK** [comment]
You didn't copy the error, just the subsequent React message saying where the error happened. Most likely you got the error from `React.Children.only` because you tried putting more than one child in Gamepad
