### ISSUE TITLE
Which brands joystick hardware it supports?

### ISSUE THREAD

**Issue by gowdruNikhil** [SBRK/react-gamepad#2]
hi i have a project where robots are controlled using keyboard and joystick. i need to know weather this support the joystick hardware and is there a restriction to use only particular brand named joystick. help me

thank you

**Comment by SBRK** [comment]
Hello, this uses the Gamepad API, which theoretically will support anything the OS supports and sees as a gamepad.

If you would like to know wether or not your gamepad/joystick will work, you should check here : http://html5gamepad.com/

That said, this library has been built with the XBOX Gamepad in mind, which has a layout that is more or less standard nowadays. I use a system of layout that maps buttons and axis to XBOX button names and axis (A, B, C, LT, RT, etc).

If you have an exotic gamepad, I would advise you to create a custom layout, but that layout will have to map to XBOX controller button names/axis. It means that if your controller has more than two joysticks, it will be difficult to use with this library without some tweaks.
Take a look at the XBOX layout file to get an example of how it is done: 
https://github.com/SBRK/react-gamepad/blob/master/src/layouts/XBOX.js

Each array maps an index to a button/axis etc. For example, if you have a joystick with a button that triggers the button with index 5 and you want to map it as "A", you would set "A" at the 5th position in the buttons array.

I realise now this is kind of a lame system and I would probably redo that part if I come back to work on that library.

Let me know if you have any other questions
